// Code generated by protoc-gen-go.
// source: protoeasy.proto
// DO NOT EDIT!

package protoeasy

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Directives struct {
	Cpp                     bool     `protobuf:"varint,1,opt,name=cpp" json:"cpp,omitempty"`
	CppRelOutDirPath        string   `protobuf:"bytes,2,opt,name=cpp_rel_out_dir_path" json:"cpp_rel_out_dir_path,omitempty"`
	Csharp                  bool     `protobuf:"varint,3,opt,name=csharp" json:"csharp,omitempty"`
	CsharpRelOutDirPath     string   `protobuf:"bytes,4,opt,name=csharp_rel_out_dir_path" json:"csharp_rel_out_dir_path,omitempty"`
	Objectivec              bool     `protobuf:"varint,5,opt,name=objectivec" json:"objectivec,omitempty"`
	ObjectivecRelOutDirPath string   `protobuf:"bytes,6,opt,name=objectivec_rel_out_dir_path" json:"objectivec_rel_out_dir_path,omitempty"`
	Python                  bool     `protobuf:"varint,7,opt,name=python" json:"python,omitempty"`
	PythonRelOutDirPath     string   `protobuf:"bytes,8,opt,name=python_rel_out_dir_path" json:"python_rel_out_dir_path,omitempty"`
	Ruby                    bool     `protobuf:"varint,9,opt,name=ruby" json:"ruby,omitempty"`
	RubyRelOutDirPath       string   `protobuf:"bytes,10,opt,name=ruby_rel_out_dir_path" json:"ruby_rel_out_dir_path,omitempty"`
	Go                      bool     `protobuf:"varint,11,opt,name=go" json:"go,omitempty"`
	GoRelOutDirPath         string   `protobuf:"bytes,12,opt,name=go_rel_out_dir_path" json:"go_rel_out_dir_path,omitempty"`
	GoImportPath            string   `protobuf:"bytes,14,opt,name=go_import_path" json:"go_import_path,omitempty"`
	Grpc                    bool     `protobuf:"varint,15,opt,name=grpc" json:"grpc,omitempty"`
	GrpcGateway             bool     `protobuf:"varint,16,opt,name=grpc_gateway" json:"grpc_gateway,omitempty"`
	NoDefaultModifiers      bool     `protobuf:"varint,17,opt,name=no_default_modifiers" json:"no_default_modifiers,omitempty"`
	ExcludePattern          []string `protobuf:"bytes,18,rep,name=exclude_pattern" json:"exclude_pattern,omitempty"`
}

func (m *Directives) Reset()                    { *m = Directives{} }
func (m *Directives) String() string            { return proto.CompactTextString(m) }
func (*Directives) ProtoMessage()               {}
func (*Directives) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Args struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *Args) Reset()                    { *m = Args{} }
func (m *Args) String() string            { return proto.CompactTextString(m) }
func (*Args) ProtoMessage()               {}
func (*Args) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CompileRequest struct {
	Tar        []byte      `protobuf:"bytes,1,opt,name=tar,proto3" json:"tar,omitempty"`
	Directives *Directives `protobuf:"bytes,2,opt,name=directives" json:"directives,omitempty"`
}

func (m *CompileRequest) Reset()                    { *m = CompileRequest{} }
func (m *CompileRequest) String() string            { return proto.CompactTextString(m) }
func (*CompileRequest) ProtoMessage()               {}
func (*CompileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CompileRequest) GetDirectives() *Directives {
	if m != nil {
		return m.Directives
	}
	return nil
}

type CompileResponse struct {
	Args []*Args `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
	Tar  []byte  `protobuf:"bytes,2,opt,name=tar,proto3" json:"tar,omitempty"`
}

func (m *CompileResponse) Reset()                    { *m = CompileResponse{} }
func (m *CompileResponse) String() string            { return proto.CompactTextString(m) }
func (*CompileResponse) ProtoMessage()               {}
func (*CompileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CompileResponse) GetArgs() []*Args {
	if m != nil {
		return m.Args
	}
	return nil
}

func init() {
	proto.RegisterType((*Directives)(nil), "protoeasy.Directives")
	proto.RegisterType((*Args)(nil), "protoeasy.Args")
	proto.RegisterType((*CompileRequest)(nil), "protoeasy.CompileRequest")
	proto.RegisterType((*CompileResponse)(nil), "protoeasy.CompileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for API service

type APIClient interface {
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	out := new(CompileResponse)
	err := grpc.Invoke(ctx, "/protoeasy.API/Compile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for API service

type APIServer interface {
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).Compile(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protoeasy.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _API_Compile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0xd3, 0x93, 0x30,
	0x10, 0xf6, 0x7d, 0xa1, 0x1f, 0x2c, 0x08, 0x1a, 0x5b, 0x1b, 0x5b, 0x1d, 0x3b, 0x78, 0xa9, 0x97,
	0x1e, 0xea, 0xd9, 0x43, 0xd5, 0x83, 0xbd, 0x39, 0xfe, 0x01, 0x26, 0x85, 0x94, 0xe2, 0x50, 0x12,
	0x93, 0x50, 0xe5, 0xb7, 0xf8, 0x67, 0x85, 0xa5, 0xb4, 0x75, 0xf0, 0xc6, 0xee, 0xf3, 0x95, 0xd9,
	0x07, 0x08, 0xa4, 0x12, 0x46, 0x70, 0xa6, 0xab, 0x35, 0x7e, 0x11, 0xe7, 0xba, 0x08, 0xff, 0x58,
	0x00, 0x5f, 0x32, 0xc5, 0x63, 0x93, 0x9d, 0xb9, 0x26, 0x2e, 0x58, 0xb1, 0x94, 0xf4, 0x61, 0xf9,
	0xb0, 0x1a, 0x93, 0xd7, 0x30, 0xa9, 0x87, 0x48, 0xf1, 0x3c, 0x12, 0xa5, 0x89, 0x92, 0x4c, 0x45,
	0x92, 0x99, 0x23, 0x7d, 0xac, 0x51, 0x87, 0xf8, 0x30, 0x8c, 0xf5, 0x91, 0x29, 0x49, 0x2d, 0x64,
	0xbf, 0x85, 0x59, 0x3b, 0xf7, 0x05, 0x36, 0x0a, 0x08, 0x80, 0xd8, 0xff, 0x68, 0x93, 0x62, 0x3a,
	0x40, 0xd1, 0x3b, 0x58, 0xdc, 0x76, 0x7d, 0xe1, 0xb0, 0x4b, 0x92, 0x95, 0x39, 0x8a, 0x82, 0x8e,
	0xba, 0xa4, 0x76, 0xee, 0x0b, 0xc6, 0x28, 0xf0, 0xc0, 0x56, 0xe5, 0xbe, 0xa2, 0x0e, 0xd2, 0xdf,
	0xc0, 0xb4, 0x99, 0xfa, 0x64, 0x40, 0x32, 0xc0, 0x63, 0x2a, 0xa8, 0x8b, 0xd4, 0x05, 0xbc, 0x48,
	0x45, 0x9f, 0xe8, 0x21, 0xf1, 0x25, 0xf8, 0x35, 0x98, 0x9d, 0xa4, 0x50, 0xa6, 0xdd, 0xfb, 0x5d,
	0x5a, 0xaa, 0x64, 0x4c, 0x03, 0xb4, 0x98, 0x80, 0xd7, 0x4c, 0x51, 0xca, 0x0c, 0xff, 0xc5, 0x2a,
	0xfa, 0xac, 0x3b, 0x65, 0x21, 0xa2, 0x84, 0x1f, 0x58, 0x99, 0x9b, 0xe8, 0x24, 0x92, 0xec, 0x90,
	0x71, 0xa5, 0xe9, 0x73, 0x44, 0x67, 0x10, 0xf0, 0xdf, 0x71, 0x5e, 0x26, 0xbc, 0xf1, 0x35, 0x5c,
	0x15, 0x94, 0x2c, 0xad, 0x95, 0x13, 0x4e, 0xc1, 0xde, 0xaa, 0x54, 0x93, 0xa7, 0x30, 0x38, 0xb3,
	0xbc, 0xe4, 0x75, 0x31, 0xcd, 0xfa, 0x2b, 0xf8, 0x9f, 0xc5, 0x49, 0x66, 0x39, 0xff, 0xce, 0x7f,
	0x96, 0x5c, 0x9b, 0xa6, 0x37, 0xc3, 0x14, 0xf6, 0xe6, 0x91, 0xf7, 0x00, 0xc9, 0xb5, 0x52, 0x6c,
	0xcb, 0xdd, 0x4c, 0xd7, 0xb7, 0x9f, 0xe0, 0xd6, 0x77, 0xf8, 0x11, 0x82, 0xab, 0x93, 0x96, 0xa2,
	0xd0, 0xbc, 0x3e, 0x97, 0xcd, 0xea, 0x4c, 0x8c, 0x72, 0x37, 0xc1, 0x9d, 0x0e, 0x9f, 0x72, 0x49,
	0x6a, 0x5c, 0xbd, 0xcd, 0x0e, 0xac, 0xed, 0xb7, 0x1d, 0xf9, 0x04, 0xa3, 0x8b, 0x0b, 0x79, 0x75,
	0xc7, 0xff, 0xf7, 0x8d, 0xf3, 0xf9, 0xff, 0xa0, 0x36, 0x34, 0x7c, 0xb2, 0x1f, 0x22, 0xf8, 0xe1,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x36, 0xac, 0xbf, 0x05, 0xad, 0x02, 0x00, 0x00,
}
